### ISSUE TITLE
Just the chip

### ISSUE THREAD

**Issue by con-f-use** [jdunmire/kicad-ESP8266#14]
This should also have a footprint and schematic symbol for the two chips (esp8266E and esp8285) without breakout/module board. Simply the bare chips.

**Comment by jdunmire** [comment]
I can see where that would be useful, but I don't think I will have time to add them in the near future. Perhaps you, or someone else can create the files and submit a pull request.

**Comment by con-f-use** [comment]
> Perhaps you, or someone else can create the files and submit a pull request.
> Done --> #17
