### ISSUE TITLE
Any plans to add ESP-12F?

### ISSUE THREAD

**Issue by salqadri** [jdunmire/kicad-ESP8266#26]
Any plans to add the ESP 12F?

**Comment by slegge** [comment]
ESP-12E can be used for ESP-12F, the only difference is the antenna

**Comment by salqadri** [comment]
Ok great; so the layout and 3d model should be the same for the two? When I generate my BOM I would need to modify it?

**Comment by slegge** [comment]
Yes, exact same layout and 3D model.  Generating your BOM will depend on which tools you're using for that and which fields it is using.
