### ISSUE TITLE
ESP12E : pin mapping

### ISSUE THREAD

**Issue by jeanmatthieud** [jdunmire/kicad-ESP8266#37]
The PIN mapping between the component and the footprint.

![2018-03-25 20_55_55-module_ rf_modules_esp-12e](https://user-images.githubusercontent.com/1443167/37878860-8a0ad336-306f-11e8-9b2d-e231b800f82f.png)

**Comment by tadas-s** [comment]
I think it's a symbol issue. Footprint appears to number pins correctly. Hopefully I'll have a PR ready soon. It's a small fix.

**Comment by jdunmire** [comment]
Closing- See comments at
https://github.com/jdunmire/kicad-ESP8266/pull/38#issuecomment-377908215
